# Generated by Django 5.0.6 on 2024-05-18 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='carousels/')),
                ('link', models.URLField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Awards', 'Awards'), ('Trophies', 'Trophies'), ('Medals', 'Medals')], max_length=10)),
                ('image', models.ImageField(upload_to='catalogue/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
