# Generated by Django 5.0.6 on 2024-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='type',
            field=models.CharField(choices=[('awards', 'awards'), ('trophies', 'trophies'), ('medals', 'medals')], max_length=10),
        ),
    ]
